[package]
name = "nonevicting_cache"
version = "0.1.0"
edition = "2021"

[dependencies.cache]
version = "0.1"
git = "http://github.com/pdx-cs-rust/cache"

[dev-dependencies.cache-tests]
version = "0.1"
git = "http://github.com/pdx-cs-rust/cache"
